### ISSUE TITLE
Per-device influxdb-enabled checkbox

### ISSUE THREAD

**Issue by js216** [js216/CeNTREX#109]

**Comment by js216** [comment]
Default `InfluxDB_enabled` option defined in 5661dfb8df6687d4f7b0d88000b5b11e07ace9fc

**Comment by ograsdijk** [comment]
Finished support for per device InfluxDB toggling in [https://github.com/js216/CeNTREX/commit/b55c2e94ae3fefd53aee0c96c1d5e4314f41c480](url)
