### ISSUE TITLE
Throw warning when device stops functioning while running main program

### ISSUE THREAD

**Issue by ograsdijk** [js216/CeNTREX#61]
Currently when a device stops functioning during a run all other devices keep running, which is exactly what we want. There is no warning when a device stops functioning though, and we only see this when Grafana throws a warning after _n_ minutes.
Throwing a warning when a device returns a certain number of nan in a row would be an indicator a device stopped running, or additionally throwing a warning when a device thread stops running.

**Comment by js216** [comment]
Implemented in 7942901.

The `Device` class now keeps track of number of sequential NaN returns. When the number becomes too great, the `Device` object puts a warning into its `warnings` list of warnings. This list is read by the instance of `Monitoring` class, which displays it in the main code, as well as pushes it to InfluxDB.

The limit for the number of sequential NaN returns is either 10 returns as per [the source code](https://github.com/js216/CeNTREX/commit/79429014e1a218b358c3414232638695da3d50a4#diff-5bc02cefb3ea9e27f1a6776eabd1935dR300), or the number defined in the `max_NaN_count` parameter in the `[device]` section of the device `.ini` file.

In addition, the main loop in the `run()` function of the `Device` class is now wrapped in a `try ... except` statement. Any `Exception` is caught there, converted to string, and added to the list of `warnings` for the `Monitoring` class to read.
